### ISSUE TITLE
Unable to import to MS-SQL from existing FS store (jsReports v2.1.0)

### ISSUE THREAD

**Issue by ChrisNeff** [jsreport/jsreport-import-export#7] opened 2018-07-23 16:24 UTC
I am unable to convert from fs based store to ms-sql-store.  The imported contents do not show up.  Have tried this only on my local environment (Windows 10).

With the following configurations:

{
    "httpPort": 5488,
    "allowLocalFilesAccess": true,
    "store": {
        "provider": "mssql"
    },
    "blobStorage": {
        "provider": "fs"
    },
    "templatingEngines": {
        "timeout": 120000,
        "strategy": "http-server",
        "numberOfWorkers": 4
    },
    "chrome": {
        "timeout": 120000
    },
    "extensions": {
        "authentication": {
            "cookieSession": {
                "secret": "<your strong secret>"
            },
            "admin": {
                "username": "admin",
                "password": "password"
            },
            "enabled": false
        },
        "sample-template": {
            "createSamples": true
        },
        "scripts": {
            "timeout": 120000
        },
        "mssql-store": {
            "uri": "XXX"
        }
    }
}

**Comment by pofider** [comment] 2018-07-26 11:45
Thank you for reporting the issue.
It is now fixed in jsreport-mssql-store@1.2.0

The issue was caused by API change in the mssql driver this package uses which was not reflected.

**Closed by pofider** 2018-07-26 11:45 UTC
